# File: src\main\resources\application.yml
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  main:
    banner-mode: off
    lazy-initialization: true
  
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

ontology:
  file-path: classpath:ontology/ad-decision-support-system.ttl
  reasoner-type: PELLET
  swrl-enabled: true
  base-iri: "http://www.semanticweb.org/cahyaw06/ontologies/2025/10/ad-decision-support-system/"

logging:
  level:
    com.alzheimer: DEBUG
    org.springframework: INFO
    org.hibernate: ERROR